### PR TITLE
Addition footer (SCSS + HTML)

### PR DESCRIPTION
**Pull request by Bauffeuvre**

### CODE REVIEW

**Review by clay-land — COMMENTED** [review]
I think for all our front end pull requests, we should include a screenshot so we can see exactly what it looks like.

**Comment by Bauffeuvre** [comment]
image
You are right !

**Comment by clay-land** [comment]
Can you align the h5 and li's? I think it would look better all of them aligned

**Comment by Bauffeuvre** [comment]
Aligned !

image

**Comment by Bauffeuvre** [comment]
Or this 
image

**Comment by clay-land** [comment]
Nice! I think the 2nd one looks better, with the icons lined up too. Nice job

**Pull request merged**
